-------------------------------------------------------------------------------
--  nano-aider - Configuration File Management (Body)
--  Copyright (C) 2024-2025 Jonathan D.A. Jewell
--  SPDX-License-Identifier: MIT OR AGPL-3.0-or-later
-------------------------------------------------------------------------------

with Ada.Text_IO;
with Ada.Directories;
with Ada.Environment_Variables;

package body Nano_Aider.Config is

   package TIO renames Ada.Text_IO;
   package Dir renames Ada.Directories;
   package Env renames Ada.Environment_Variables;

   Current_Config_Path : String (1 .. 1024);
   Config_Path_Length  : Natural := 0;
   Modified            : Boolean := False;
   Nano_Ver            : String (1 .. 16) := (others => ' ');
   Nano_Ver_Length     : Natural := 0;

   ---------------------------------------------------------------------------
   procedure Load_Default is
      Home : constant String := Env.Value ("HOME", "/home");
   begin
      --  Try XDG config first
      declare
         XDG_Config : constant String :=
           Env.Value ("XDG_CONFIG_HOME", Home & "/.config");
         XDG_Path   : constant String := XDG_Config & "/nano/nanorc";
      begin
         if Dir.Exists (XDG_Path) then
            Load_From_File (XDG_Path);
            return;
         end if;
      end;

      --  Fall back to ~/.nanorc
      declare
         User_RC : constant String := Home & "/.nanorc";
      begin
         if Dir.Exists (User_RC) then
            Load_From_File (User_RC);
            return;
         end if;
      end;

      --  Try system config
      if Dir.Exists ("/etc/nanorc") then
         Load_From_File ("/etc/nanorc");
      end if;
   end Load_Default;

   ---------------------------------------------------------------------------
   procedure Load_From_File (Path : String) is
      File : TIO.File_Type;
   begin
      if Path'Length > Current_Config_Path'Length then
         return;
      end if;

      Current_Config_Path (1 .. Path'Length) := Path;
      Config_Path_Length := Path'Length;

      if Dir.Exists (Path) then
         TIO.Open (File, TIO.In_File, Path);
         --  TODO: Parse nanorc format
         TIO.Close (File);
      end if;
   exception
      when others =>
         if TIO.Is_Open (File) then
            TIO.Close (File);
         end if;
   end Load_From_File;

   ---------------------------------------------------------------------------
   procedure Load_System_Config is
   begin
      Load_From_File ("/etc/nanorc");
   end Load_System_Config;

   ---------------------------------------------------------------------------
   procedure Load_User_Config is
   begin
      Load_Default;
   end Load_User_Config;

   ---------------------------------------------------------------------------
   procedure Save_To_File (Path : String) is
      File : TIO.File_Type;
   begin
      TIO.Create (File, TIO.Out_File, Path);
      TIO.Put_Line (File, "# nano configuration generated by nano-aider");
      TIO.Put_Line (File, "# https://github.com/hyperpolymath/nano-aider");
      TIO.New_Line (File);
      --  TODO: Write all configured options
      TIO.Close (File);
      Modified := False;
   exception
      when others =>
         if TIO.Is_Open (File) then
            TIO.Close (File);
         end if;
   end Save_To_File;

   ---------------------------------------------------------------------------
   procedure Save_User_Config is
      Home : constant String := Env.Value ("HOME", "/home");
   begin
      Save_To_File (Home & "/.nanorc");
   end Save_User_Config;

   ---------------------------------------------------------------------------
   procedure Export_Nanorc (Path : String) is
   begin
      Save_To_File (Path);
   end Export_Nanorc;

   ---------------------------------------------------------------------------
   procedure Export_Micro_Json (Path : String) is
      File : TIO.File_Type;
   begin
      TIO.Create (File, TIO.Out_File, Path);
      TIO.Put_Line (File, "{");
      TIO.Put_Line (File, "  ""comment"": ""micro config generated by nano-aider"",");
      --  TODO: Write micro JSON format
      TIO.Put_Line (File, "}");
      TIO.Close (File);
   exception
      when others =>
         if TIO.Is_Open (File) then
            TIO.Close (File);
         end if;
   end Export_Micro_Json;

   ---------------------------------------------------------------------------
   procedure Export_Markdown (Path : String) is
      File : TIO.File_Type;
   begin
      TIO.Create (File, TIO.Out_File, Path);
      TIO.Put_Line (File, "# nano Configuration Export");
      TIO.Put_Line (File, "");
      TIO.Put_Line (File, "Generated by nano-aider");
      TIO.Put_Line (File, "");
      --  TODO: Write markdown documentation
      TIO.Close (File);
   exception
      when others =>
         if TIO.Is_Open (File) then
            TIO.Close (File);
         end if;
   end Export_Markdown;

   ---------------------------------------------------------------------------
   function Get_Config_Path return String is
   begin
      return Current_Config_Path (1 .. Config_Path_Length);
   end Get_Config_Path;

   ---------------------------------------------------------------------------
   function Is_Modified return Boolean is
   begin
      return Modified;
   end Is_Modified;

   ---------------------------------------------------------------------------
   function Get_Nano_Version return String is
   begin
      return Nano_Ver (1 .. Nano_Ver_Length);
   end Get_Nano_Version;

   ---------------------------------------------------------------------------
   procedure Merge_Config (Path : String) is
   begin
      --  TODO: Merge another config file into current
      null;
   end Merge_Config;

   ---------------------------------------------------------------------------
   procedure Clear_Config is
   begin
      Config_Path_Length := 0;
      Modified := False;
   end Clear_Config;

end Nano_Aider.Config;
